#sysbench压测的时间，以s计
runtime: 10

#sysbench的表数量
table: 10

#sysbench的数据量大小
tableSize: 1000

#sysbench压测的驱动类型, "pgsql" 或者 "mysql"
driver: "pgsql"

#sysbench报告的压测报告间隔,以s计
reportInterval: 1

#单个测试完毕后的休息间隔，以s计
relaxTime: 10

#指定要运行的loadworker:
#        - write_only
#        - read_only
#        - read_write
#        - point_select
#        - update_index
loadworker:
        #- write_only
        #- read_only
        #- read_write
        - insert
        - point_select
        #- update_index

#sysbench每个计算节点要压测的线程数
threads:
        - 100
        - 200
        - 300

#以下是计算节点的相关信息
#第二级为计算节点名字，也就是后面新建目录的名字。随意取
config:
        comp1:
        #第三级开始就是计算节点的信息,key不可以随便改
                host: "192.168.0.132"
                port: 8881
                user: "abc"
                #密码有就填，没有也随便写，反正不能为空
                pwd:  "abc"
                dbname: "postgres"
        
        computer2:
                host: "192.168.0.134"
                port: 8881
                user: "abc"
                pwd:  "abc"
                dbname: "postgres"

        compnode3:
                host: "192.168.0.140"
                port: 8881
                user: "abc"
                pwd:  "abc"
                dbname: "postgres"
