rm -rf cloudnative
git clone https://gitee.com/zettadb/cloudnative.git
cd cloudnative/cluster/clustermgr
VERSION=1.1.1
echo downloading hadoop ...
wget -q http://zettatech.tpddns.cn:14000/thirdparty/hadoop-3.3.1.tar.gz
echo downloading jdk ...
wget -q http://zettatech.tpddns.cn:14000/thirdparty/jdk-8u131-linux-x64.tar.gz
echo downloading mysql-connector-python-2.1.3 ...
wget -q http://zettatech.tpddns.cn:14000/thirdparty/mysql-connector-python-2.1.3.tar.gz
echo downloading prometheus ...
wget -q http://zettatech.tpddns.cn:14000/thirdparty/prometheus.tgz
echo downloading haproxy ...
wget -q http://zettatech.tpddns.cn:14000/thirdparty/haproxy-2.5.0-bin.tar.gz
echo downloading kunlun-cluster-manager ...
wget -q http://zettatech.tpddns.cn:14000/dailybuilds/enterprise/kunlun-cluster-manager-$VERSION.tgz
echo downloading kunlun-node-manager ...
wget -q http://zettatech.tpddns.cn:14000/dailybuilds/enterprise/kunlun-node-manager-$VERSION.tgz
echo downloading kunlun-server ...
wget -q http://zettatech.tpddns.cn:14000/dailybuilds/enterprise/kunlun-server-$VERSION.tgz
echo downloading kunlun-storage ...
wget -q http://zettatech.tpddns.cn:14000/dailybuilds/enterprise/kunlun-storage-$VERSION.tgz
echo downloading filebeat-7.10.1 ...
wget -q http://zettatech.tpddns.cn:14000/thirdparty/efk/filebeat-7.10.1-linux-x86_64.tar.gz
echo downloading kunlun-proxysql ...
wget -q http://zettatech.tpddns.cn:14000/dailybuilds/enterprise/kunlun-proxysql-$VERSION.tgz
